name: CI-test

# Run this workflow every time a commit is pushed to test
on:
  push:
    branches:
      - test

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/superhow/symbol
            azure-pipeline-name: 'symbol-docker-test'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}